### ISSUE TITLE
Failing jobs show as succeeded

### ISSUE THREAD

**Issue by zach-source** [razee-io/razeedeploy-delta#90]
**Describe the bug**
Running the razeedeploy-delta image as a job does not set the exit code properly so if it fails it reports as successful.

**To Reproduce**
1. Run the job with a custom file source url that is invalid
2. Check the job status

**Expected behavior**
Container should report fatal errors as exit code != 0 and job should report a failed count of 1.

**Kubernetes Version (kubectl version):**
 - Client: v1.18.0
 - Server: v1.16.2

**Comment by alewitt2** [comment]
thanks, added to the backlog. PRs are welcome, otherwise i will get to it at some point.

**Comment by zach-source** [comment]
Definitely, I'll see what I can do in the next few days.

**Comment by cherylfbrown** [comment]
@alewitt2 @mckaymic We had a user hit an issue with the Razee install job in prod and couldn't get to their job logs to see what was wrong since it was reported as successful. Any ETA on this one?

**Comment by alewitt2** [comment]
why couldnt they get the job logs? even a successful job pod isnt cleaned up and you can look at the logs.

**Comment by cherylfbrown** [comment]
I think @zach-source is cleaning it up in case of success so that we aren't leaving things around. Zach any more details to add here?

**Comment by alewitt2** [comment]
ah that would do it. ive created a PR that should hopefully fix this.

**Comment by alewitt2** [comment]
https://github.com/razee-io/razeedeploy-delta/releases/tag/1.1.3

**Comment by zach-source** [comment]
Ah thanks Alex - quick turn around. I'll test it out.

**Comment by alewitt2** [comment]
Let me know how it goes

**Comment by zach-source** [comment]
Looks great Alex, thanks a lot.
